import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import logo from '../public/logo.png'
import Link from 'next/link'
import {SearchBar} from '../components/SearchBar'
import { Icon } from '@iconify/react';

export default function Home() {
  return (
    <div>
      <Head>
      <title>Huntershare</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <h1 className={styles.logo}>Huntershare</h1>
        <div  className={styles.logoPic}>
        <Image 
          src={logo}
          alt="huntershare logo"
          />
        </div>
        <nav className={styles.nav}>
          <Link href='#'>
            Login
          </Link>
          <span> / </span>
          <Link href='#'>
            Sign-up
          </Link>
        </nav>
      </header>
      <main>
        <div className={styles.hero}>
            <h1 className={styles.mainText}>
            Share your tips, tricks, and findings with the community.
            </h1>
            <h2>Or</h2>
            <h2>Search for a specific hint or writeup</h2>
            <div className={styles.searchbar}>
               <input type="text" placeholder='Type...' />
            </div>
            <h2>Nothing in mind? ? See the latest posts here</h2>
            <Link href='#' passHref>
              <Icon className={styles.seeMore} icon="dashicons:arrow-down-alt2" width="96" />
            </Link>
        </div>
      </main>
    </div>
  )
}
